# Generated by Django 3.0 on 2020-02-18 06:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('skills', models.TextField()),
                ('joined', models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 11, 32, 52, 702104))),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='details.UserDetails')),
                ('cardNUmber', models.CharField(max_length=16)),
                ('expiryDate', models.Field(max_length=13)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
