# Generated by Django 3.0 on 2020-02-18 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='details.UserDetails')),
                ('ordeId', models.CharField(max_length=12, unique=True)),
                ('trackingID', models.CharField(max_length=40)),
                ('item', models.CharField(max_length=50)),
                ('orderDate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 11, 42, 25, 531978)),
        ),
    ]
