# Generated by Django 3.0 on 2020-02-18 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200218_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='empStatus',
            field=models.CharField(default='unemployed', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 18, 13, 0, 43, 726309)),
        ),
    ]
